kind: ConfigMap
apiVersion: v1
metadata:
  name: cpf-configs
data:
  cpf_config.yaml: |-
    api_providers:
      - name: "BC Address Geocoder"
        host: "https://geocoder.api.gov.bc.ca/"
        endpoints:
          - name: "Geocode"
            path: "addresses"
            default_params:
              outputFormat: "json"
              addressString: ""
              locationDescriptor: "any"
              maxResults: 1
              interpolation: "adaptive"
              echo: "true"
              brief: "false"
              autoComplete: "false"
              exactSpelling: "false"
              fuzzyMatch: "false"
              setBack: 0
              outputSRS: 4326
              minScore: 1
              matchPrecision: ""
              matchPrecisionNot: ""
              siteName: ""
              unitDesignator: "--"
              unitNumber: ""
              unitNumberSuffix: ""
              civicNumber: ""
              civicNumberSuffix: ""
              streetName: ""
              streetType: ""
              streetDirection: "--"
              streetQualifier: ""
              localityName: ""
              provinceCode: "BC"
              localities: ""
              notLocalities: ""
              bbox: ""
              centre: ""
              maxDistance: ""
              extrapolate: "--"
              pacelPoint: ""
            output_headers:
              - "sequenceNumber"
              - "resultNumber"
              - "yourId"
              - "fullAddress"
              - "intersectionName"
              - "score"
              - "matchPrecision"
              - "precisionPoints"
              - "faults"
              - "siteName"
              - "unitDesignator"
              - "unitNumber"
              - "unitNumberSuffix"
              - "civicNumber"
              - "civicNumberSuffix"
              - "streetName"
              - "streetType"
              - "isStreetTypePrefix"
              - "streetDirection"
              - "isStreetDirectionPrefix"
              - "streetQualifier"
              - "localityName"
              - "localityType"
              - "electoralArea"
              - "provinceCode"
              - "location"
              - "locationPositionalAccuracy"
              - "locationDescriptor"
              - "siteID"
              - "blockID"
              - "intersectionID"
              - "fullSiteDescriptor"
              - "accessNotes"
              - "siteStatus"
              - "siteRetireDate"
              - "changeDate"
              - "isOfficial"
              - "degree"
              - "executionTime"
              - "sid"
          - name: "Geocoder occupants"
            path: "occupants/addresses"
            default_params:
              outputFormat: "json"
              maxResults: 1
              matchPrecision: "exact"
      - name: "BC Route Planner"
        host: "https://api.provider2.com"
    worker_options:
      max_worker_row_count: 1000
    app_options:
      public_url_host: "cpf-dev.apps.gold.devops.gov.bc.ca"
      public_url_protocol: "https"

